### ISSUE TITLE
Can you add Lineage 19 icons to Android 12

### ISSUE THREAD

**Issue by PaLo6415** [WSTxda/Lineage-Icons#2]
Please add Lineage 19 icons to Android 12

**Comment by WSTxda** [comment]
Lineage 19.1 icons relased with Android 12L, so icon pack use this icons in same Android version

**Comment by PaLo6415** [comment]
But my phone won't get Android 12L

**Comment by WSTxda** [comment]
¯\_(ツ)_/¯

**Comment by WSTxda** [comment]
¯\_(ツ)_/¯

**Comment by WSTxda** [comment]
I'm sorry but I won't change that
