### ISSUE TITLE
Can't see the icons

### ISSUE THREAD

**Issue by edent** [WSTxda/Lineage-Icons#5]
Hello! I'm trying to use this app. I've installed it correctly and my launcher (NeoLauncher) can see the IconPack.

But when I try to browse for any icons, I don't get any results. My launcher can see other icon packs I've installed.

Any idea what's going on?

I'm on Lineage 20, and NeoLauncher 0.9.3.

Thanks :smiley:

**Comment by WSTxda** [comment]
i will fix with in next release
